version: '3'
services:
  # Служба для MongoDB
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Служба для Flask приложения
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Измененный порт здесь
    environment:
      MONGO_URI: "mongodb://admin:admin_password@mongodb:27017/mydb"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
